Readmeの更新とテキストファイルの追加
github-user-001/test-rep1 pull request #3
Opened 2019-05-29 06:26 UTC by github-user-001

Readmeの更新とテキストファイルの追加

2019-05-29 09:08 UTC, akiyoshi-yusuke requested changes
test

2019-05-29 09:08 UTC, akiyoshi-yusuke commented on README.md
> +hogehoge
hogehogeを大文字にしてください
```suggestion
**hogehoge**
```

2019-05-30 00:24 UTC, akiyoshi-yusuke commented on README.md
> +hogehoge
hogehogeを大文字にしてください
```suggestion
**hogehoge**
```

2019-05-30 00:29 UTC, akiyoshi-yusuke commented on README.md
> +hogehoge
hogehogeを大文字にしてください
```suggestion
**hogehoge**
```

2019-05-30 00:40 UTC, akiyoshi-yusuke requested changes
コメントしたので指摘箇所を修正してください

2019-05-30 00:40 UTC, akiyoshi-yusuke commented on README.md
> +hogehoge
hogehogeを大文字にしてください
```suggestion
**hogehoge**
```

2019-05-30 01:03 UTC, github-user-001 commented on README.md
> +hogehoge
修正しました！確認してお願いします:bow:

2019-05-30 01:10 UTC, akiyoshi-yusuke approved these changes
確認しました。承認します。

2019-05-30 01:11 UTC, merged